config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  resources :users
    get    'sign_in'  => 'sessions#new' 
    post   'sign_in'  => 'sessions#create'
    delete 'sign_out' => 'sessions#destroy'
    get    'home'     => "home#index"

  resource :confirmation, :only => [:show]
    root :to => 'sessions#new'

  

end

app/models/room.rb
class Room < ActiveRecord::Base

	validates :title, :location, :presence => true
  	validates_length_of :description, :minimum => 3, :allow_blank => false

	has_many :vinculos, foreign_key: :id
	has_many :users, through: :vinculos

	def complete_name
		"#{title}, #{location}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	has_secure_password 

	validates_presence_of :email, :full_name, :location, :bio, :password_digest
	
	validates_length_of :bio, :minimum => 3, :allow_blank => false
	
	validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
	
	validates_uniqueness_of :email

	  

	before_save { self.email = email.downcase }
	
	before_create :generate_token

	has_many :vinculos, foreign_key: :id
	has_many :rooms, through: :vinculos
	
	def generate_token
		self.confirmation_token = SecureRandom.urlsafe_base64
	end

	def confirm!
		return if confirmed?
		self.confirmed_at = Time.current
		self.confirmation_token = ''
		save!		
	end

	def confirmed?
		confirmed_at.present?
	end

end

app/models/user_session.rb
class UserSession
	
	include ActiveModel::Validations
	include ActiveModel::Conversion
	
	extend ActiveModel::Naming
	extend ActiveModel::Translation
	
	attr_accessor :email, :password
	validates_presence_of :email, :password
	
	def persisted?
		false
	end
end

app/models/vinculos.rb
class Vinculos < ActiveRecord::Base
	belongs_to :user, foreign_key: :id 
	belongs_to :room, foreign_key: :id 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
  	unless logged_in?
  		redirect_to root_path
  	end
  end

  def correct_user?
  	@user = User.find(params[:id])
  		unless @current_user == @user  			
  		end
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
	def show
		user = User.find_by_confirmation_token(params[:token])

		if user.present?
			user.confirm!
			redirect_to user,
				:notice => 'confirme o email.'
		else
			redirect_to root_path
		end
	end
end		

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@rooms = Room.where(status: true).last(3)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authorize

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.where(status: true)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
     @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if set_room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    set_room.update_attributes(status: false)
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 before_action :block_access, except: [:destroy]

  def new
  	  @user = User.new
  end

  def create
  	@user = User.where(status: true).find_by(email: params[:session][:email]) 
  	if @user && @user.authenticate(params[:session][:password])
  		 sign_in @user,
                   flash[:notice] = "logado!"
                  redirect_to home_path
  	else
  		flash[:notice] = "usuario e/ou senha invalido."
  		render 'new'

  	end
  end

  def destroy
  	sign_out
  	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]
  before_action :correct_user?, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      SignupMailer.confirm_email(@user).deliver
      redirect_to @user,
       :notice => 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def show
    set_user
  end

  def edit
    set_user
  end

  def update

    if @user.update_attributes(user_params)
      redirect_to @user, :notice => 'Usuario atualizado com sucesso!'
    else
      render :update
    end
  end

  def index
    @users = User.where(status: true)
  end

  def destroy
    set_user.update_attributes(status: false)
    redirect_to @user, :notice => 'Usuario exucluido com sucesso!'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params[:user][:password_digest] = BCrypt::Password.create(params[:user][:password_digest]).to_s
    params.require(:user).permit(:full_name, :email, :bio, :password_digest, :location)
  end
end

app/controllers/vinculos_controller.rb
class VinculosController < ApplicationController
	
	def index
		@vinculos = Vinculos.all
	end
	
	def new
		@vinculo = Vinculos.new
	end
	
	def create
		if @vinculos.status == false
			@vinculo =  User.new(user_params)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

=begin
	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag :div, model.errors[attribute].first,
			:class => 'error_message'
		end
	end
=end


end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(params, id)
		session[:user_id] = @user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def block_access
		if current_user.present?
			redirect_to home_path
	end

	def logged_in?
		!current_user.nil?
		end
	end

	def sign_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/vinculo_helper.rb
module VinculoHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title>Pedula.net</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
</head>
<body>
	<% if flash[:notice] %>
	<p class="bg-success"> <%= flash[:notice] %></p>
<% end %>
<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Quartos recém postados</h2></button>
 	<div class="row clearfix">
 		<div class="col-md-0 column">
		</div>
		<div class="col-md-12 column">
			<table class="table">
				<thead>
					<tr>
						<th>
							
						</th>
						<th>
							Título
						</th>
						<th>
							Local
						</th>
					</tr>
				</thead>
		<% @rooms.each do |room| %>
				<tbody>
					<tr class="active">
						<td>
							
						</td>
						<td>
							<li><%= link_to "#{room.title}",room %> </li>
						</td>
						<td>
							<li><%= "#{room.location}" %> </li>
						</td>
					</tr>
				</tbody>
		<% end %>
		 	</table>
		</div>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	
	<link href='http://fonts.googleapis.com/css?family=Pacifico'
	rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
  <meta charset="utf-8">
  <title>pedula.net</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  	<div class="container">
	<div class="row clearfix">
		<div class="col-md-0 column">
		</div>
		<div class="col-md-11 column">
			<h3>
				<h1> <a href="">Pedula.net</a></h1>
			</h3>
		</div>
	</div>
	<BR />
  <% if logged_in? %>
  <div align="right">
					 
					<a class="btn btn-warning" <%= link_to "Sair", sign_out_path, method: "delete" %></a>
			</div>
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="panel-group" id="panel-823373">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title" data-toggle="collapse" data-parent="#panel-823373" href="#panel-element-297118">
						 	<li><%= link_to "Quartos", rooms_path %> </li>

						 </a>
					</div>
<!-- 					<div id="panel-element-297118" class="panel-collapse in">
						<div class="panel-body">
							Anim pariatur cliche...
						</div>
					</div> -->
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-823373" href="#panel-element-9517">
						 	<li><%= link_to "Usuarios", users_path %> </li>

						 </a>
					</div>
					

					<!-- <div id="panel-element-9517" class="panel-collapse collapse">
						<div class="panel-body">
							Anim pariatur cliche...
						</div>
					</div> -->

				</div>
			</div>
		</div>
	</div>
</div>

<% end %>
</head>

<body>
	<div id="content">
		<% if notice.present? %>
		<p id="notice"><%= notice %> </p>
		<% end %>
		<% if alert.present? %>
		<p id="alert"><%= alert %> </p>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= bootstrap_form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-2 column">
  </div>
    <div class="col-md-8 column">
      <div class="field">
          <%= f.text_field :title %>
      </div>
      <div class="field">

        <%= f.text_field :location %>
      </div>
      <div class="field">

        <%= f.text_area :description %>
      </div>
      <div class="actions">
        <%= f.submit %>
        <%= link_to 'Voltar', rooms_path %>
      </div>
    </div>
<% end %>

app/views/rooms/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>pedula.net</title>
</head>
<body>
	<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Editar</h2></button>
</body>
</html>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Colcho.net</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
</head>
<body>
<h2></h2>
<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Listar quartos</h2></button>
  <div class="row clearfix">
    <div class="col-md-12 column">
      <table class="table">
        <thead>
          <tr>
            <th>Título</th>
            <th>Local</th>
            <th>descrição</th>
            <th colspan="3"></th>
          </tr>
        </thead>

    <% @rooms.each do |room| %>
        
        <tbody>
          <tr class="active">
            <td>
              <li><%= link_to "#{room.title}",room %> </li>
            </td>
            <td>
              <li><%= "#{room.location}" %> </li>
            </td>
            <td>
              <li><%= "#{room.description}" %> </li>
            </td>
            <td><%= link_to 'Visualizar', room %></td>
            <td><%= link_to 'Edit', edit_room_path(room) %>
            </td>
            <td><%= link_to 'Excluir', room, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        </tbody>
    <% end %> 
      </table>
    </div>
  </div>
    <a class="btn btn-default" <%= link_to 'Novo quarto', new_room_path %></a>
    <a class="btn btn-default" <%= link_to "Voltar", home_path %> </a>
</body>
</html>

app/views/rooms/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pedula.net</title>
</head>
<body>
	<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Cadastro</h2></button>
</body>
</html>

<%= render 'form' %>

app/views/rooms/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>pedula.net</title>
</head>
<body>
	<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Visualizar</h2></button>
</body>
</html>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Editar', edit_room_path(@room) %> 
<%= link_to 'Voltar', rooms_path %>

app/views/users/_form.html.erb
 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2>Infelizmente não foi possível completar
 a ação pois o formulário possui os seguintes erros:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message|%>
 <li><%= message %> </li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <%= bootstrap_form_for @user do |f| %>
 <div class="col-md-2 column">
		</div>
		<div class="col-md-8 column">
 	<p>

 	<%= f.text_field :full_name %>
 	</p>
 	<p>
 
 	<%= f.text_field :location %>
 	</p>
 	<p>

 	<%= f.text_field :email %>
 	</p>
 	<p>

 	<%= f.password_field :password_digest %>
 	</p>
 	
 	<p>

 	<%= f.text_area :bio %>
 	</p>
 	<p>
 		<%= f.submit %>
 		<%= link_to "Voltar", root_path %>
 	</p>
 	</div>
 <% end %>

app/views/users/edit.html.erb
<<!DOCTYPE html>
<html>
<head>
	<title>Pedula.net</title>
</head>
<body>
	<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Editar</h2></button>
</body>
</html>

<%= render 'form' %>
<%= link_to "Voltar", @user %>

app/views/users/index.html.erb
<!-- <h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>nome completo</th>
      <th>e-mail</th>
      <th>Location</th>
      <th>bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.bio %></td>
           <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo cadastro', new_user_path %>
<%= link_to "Voltar", root_path %> -->

 <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Colcho.net</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
</head>
<body>
<h2></h2>
<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Listar usuarios</h2></button>
  <div class="row clearfix">
    <div class="col-md-12 column">
      <table class="table">
        <thead>
          <tr>
            <th>Nome completo</th>
            <th>E-mail</th>
            <th>local</th>
            <th>biografia</th>
            <th colspan="3"></th>
          </tr>
        </thead>

     <% @users.each do |user| %>
        
        <tbody>
          <tr class="active">
            <td>
              <li><%= link_to "#{user.full_name}",user %> </li>
            </td>
            <td>
              <li><%= "#{user.email}" %> </li>
            </td>
            <td>
              <li><%= "#{user.location}" %> </li>
            </td>
            <td>
              <li><%= "#{user.bio}" %> </li>
            </td>
            <td><%= link_to 'Visualizar', user %></td>
            <td><%= link_to 'Editar', edit_user_path(user) %></td>
            <td><%= link_to 'Excluir',user, method: :delete, data: { confirm: 'tem certeza?' } %></td>
          </tr>
        </tbody>
    <% end %> 
      </table>
    </div>
  </div>
    <a class="btn btn-default" <%= link_to 'cadastrar usuario', new_user_path %></a>
    <a class="btn btn-default" <%= link_to "Voltar", root_path %> </a>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pedula.net</title>
</head>
<body>
	<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Cadastro</h2></button>
</body>
</html>

<%= render 'form' %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>pedula.net</title>
</head>
<body>
	<button type="button" class="btn btn-primary btn-lg btn-block"><h2>Visualizar</h2></button>
</body>
</html>

<p id="notice"><%= notice %> </p>
<h2>Perfil: <%= @user.full_name %> </h2>
<ul>
<li>Localização: <%= @user.location %> </li>
<li>Bio: <%= @user.bio %> </li>
</ul>
<%= link_to 'Editar Perfil', edit_user_path(@user) %>
<%= link_to 'Home', root_path %>